Todo list
LeoKuD/todo-list pull request #1
Opened 2021-12-27 08:25 UTC by LeoKuD

[Link to the deploy](https://leokud.github.io/todo-list/)

**Done:** 

- adding, deleting, editing tasks;
- storage tasks in localStorage;
- displaying the number of unfinished and completed tasks;
- dark theme.

2021-12-27 08:44 UTC, Dev1LtJ commented
@LeoKuD, hello. Normalized is linked by default on HTML. You can delete it. Also, please, upload the original HTML file main branch.

2022-01-05 08:13 UTC, Dev1LtJ requested changes
Hello! Good work. I left some comments. You didn't resolve all that we previously discussed. Fix it, please.

2022-01-05 08:13 UTC, Dev1LtJ commented on js/index.js
> +  myForm.removeEventListener('submit', taskSubmit);
We have discussed, that you don't need to always remove and add event listeners here. This logic is vulnerable to bugs. Try to change it.

2022-01-05 08:13 UTC, Dev1LtJ commented on js/index.js
> +  listenerSubmitEditTask = submitEditTask.bind(null, index);
try to avoid this constructions.

2022-01-05 08:13 UTC, Dev1LtJ commented on js/index.js
> +      : (item.checked = false);
You can short this code.

2022-01-05 08:13 UTC, Dev1LtJ commented on js/index.js
> +    e.target.id === 'close-right'
It's better to create enums

2022-01-05 08:13 UTC, Dev1LtJ commented on js/index.js
> +    editTask(e.target.getAttribute('data-index'));
It's better to create enums

2022-01-05 08:13 UTC, Dev1LtJ commented on js/index.js
> +  titleHeaderForm.innerText = `Add task`;
It's better to create enums

2022-01-05 08:13 UTC, Dev1LtJ commented on js/index.js
> +    myForm.removeEventListener('submit', taskSubmit);
We have discussed, that you don't need to always remove and add event listeners here. This logic is vulnerable to bugs. Try to change it.

2022-01-05 08:13 UTC, Dev1LtJ commented on scss/style.scss
> +$bc-color-primary-light: #fff;
$b**g**-color-... if you use it as background-color

2022-01-05 08:13 UTC, Dev1LtJ commented on scss/style.scss
> +  transition: $transition / 1;
0.5 / 1 = 0.5. Why do you do it?

2022-01-05 11:40 UTC, LeoKuD commented on .gitignore
> +package-lock.json
fix

2022-01-05 11:41 UTC, LeoKuD commented on js/index.js
> +const localStorageValues =  {
```
const LOCALSTORAGEKEYS =  {
  tasks: 'tasks',
  sorting: 'sorting',
  theme: 'theme'
}
```

2022-01-05 11:55 UTC, LeoKuD commented on js/index.js
> +let defaultTheme;
```
let selectedSort;
let selectedTheme;
```

2022-01-05 12:04 UTC, LeoKuD commented on js/index.js
> +const down = 'down';
```
const KEYSVARIABLES = {
  dark: 'dark',
  light: 'light',
  up: 'up',
  down: 'down'
}
```

2022-01-05 12:12 UTC, LeoKuD commented on js/index.js
> +  : (tasks = JSON.parse(localStorage.getItem(localStorageValues.tasks)));
```
tasks = JSON.parse(localStorage.getItem(LOCALSTORAGEKEYS.tasks)) || [];
selectedSort = JSON.parse(localStorage.getItem(LOCALSTORAGEKEYS.sorting)) || LOCALSTORAGEKEYS.up;
```

2022-01-05 12:13 UTC, LeoKuD commented on js/index.js
> +  : (defaultSort = JSON.parse(localStorage.getItem(localStorageValues.sorting)));
`selectedSort = JSON.parse(localStorage.getItem(LOCALSTORAGEKEYS.sorting)) || LOCALSTORAGEKEYS.up;`

2022-01-05 12:14 UTC, LeoKuD commented on js/index.js
> +const makeId = () => {
```
const generateId = () => {
  let ID = '';
```

2022-01-05 12:15 UTC, LeoKuD commented on js/index.js
> +  this.id = makeId();
```
function Task([title, text, priority]) {
  this.id = generateId();
```

2022-01-05 12:45 UTC, LeoKuD commented on js/index.js
> +  let characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
`  const characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
`

2022-01-05 12:46 UTC, LeoKuD commented on js/index.js
> +  }
```
  if (tasks.length) {
    tasks.forEach((item, index) => {
      const taskItem = taskTemplate(item, index);
      selectedSort === KEYSVARIABLES.up ?
        (!item.isDone
          ? listCurrentTasks.insertAdjacentHTML('beforeend', taskItem)
          : listCompletedTasks.insertAdjacentHTML('beforeend', taskItem))
      :
        (!item.isDone
          ? listCurrentTasks.insertAdjacentHTML('afterbegin', taskItem)
          : listCompletedTasks.insertAdjacentHTML('afterbegin', taskItem))
      
    });
  }
```

2022-01-05 12:49 UTC, LeoKuD commented on js/index.js
> +  ).length;
`  const countCompletedTasks = tasks.filter((item) => item.isDone).length;
`

2022-01-05 13:00 UTC, LeoKuD commented on js/index.js
> +}
```
function checkDate(date) {
  if (date < 10) {
    return `0${date}`
  }
  return date
}

function getDate(stamp) {
  const date = new Date(stamp);
  const month =
    date.getMonth() < 9 ? `0${date.getMonth() + 1}` : date.getMonth() + 1;
  const day = checkDate(date.getDate());
  const hours = checkDate(date.getHours());
  const minutes = checkDate(date.getMinutes());
  const fullYear = date.getFullYear();
  return ` ${hours}:${minutes} ${day}.${month}.${fullYear}`;
}
```

2022-01-05 13:02 UTC, LeoKuD commented on js/index.js
> +};
fix

2022-01-05 13:35 UTC, LeoKuD commented on js/index.js
> +  titleHeaderForm.innerText = `Add task`;
```

btnAddTask.addEventListener('click', () => {
  btnCloseForm.innerText = KEYSVARIABLES.close;
  btnSubmitForm.innerText = KEYSVARIABLES.addTaks;
  titleHeaderForm.innerText = KEYSVARIABLES.addTaks;
  myForm.addEventListener('submit', taskSubmit);
});
```

2022-01-05 14:18 UTC, LeoKuD commented on js/index.js
> +});
```
toggleTheme.addEventListener('click', () => {
  body.classList.toggle(selectedTheme);
  selectedTheme === KEYSVARIABLES.light
    ? (selectedTheme = KEYSVARIABLES.dark)
    : (selectedTheme = KEYSVARIABLES.light);
  body.classList.toggle(selectedTheme);
  updateLocalStorage(LOCALSTORAGEKEYS.theme, selectedTheme);
});
```

2022-01-05 14:41 UTC, LeoKuD commented on js/index.js
> +});
```
document.addEventListener('DOMContentLoaded', () => {
  selectedTheme =
    JSON.parse(localStorage.getItem(LOCALSTORAGEKEYS.theme)) ||
    KEYSVARIABLES.light;
  body.classList.add(selectedTheme);
});

```

2022-01-05 14:43 UTC, LeoKuD commented on css/style.css
> +}
```
.light {
  transition: $transition;
  .Low {
    background-color: $priority-color-primary-light;
  }

  .Medium {
    background-color: $priority-color-secondary-light;
  }

  .High {
    background-color: $priority-color-tertiary-light;
  }
}
```

2022-01-05 14:44 UTC, LeoKuD commented on scss/style.scss
> +  transition: $transition / 1;
fix

2022-01-05 14:55 UTC, LeoKuD commented on js/index.js
> +function taskTemplate(item, index) {
```
    tasks.forEach((item, index) => {
      const taskItem = taskTemplate(item, index);
      selectedSort === KEYSVARIABLES.up
        ? !item.isDone
          ? listCurrentTasks.append(taskItem)
          : listCompletedTasks.append(taskItem)
        : !item.isDone
        ? listCurrentTasks.prepend(taskItem)
        : listCompletedTasks.prepend(taskItem);
    });
```

```
  const taskNode = document.createElement('li');
  taskNode.className = `list-group-item d-flex w-100 mb-2 ${item.priority}`;
  taskNode.innerHTML = `<div class="w-100 mr-2">
```

2022-01-05 16:17 UTC, LeoKuD commented on js/index.js
> +  myForm.removeEventListener('submit', taskSubmit);
```
myForm.addEventListener('submit', (e) => {
  e.preventDefault()
  console.log(e.submitter.id);
    if (e.submitter.id === btnSubmitForm.id) {
      taskSubmit();
    } else if (e.submitter.id === btnSubmitEditForm.id){
      listenerSubmitEditTask()
    }
})
```

Now only one event listener submit

2022-01-05 16:43 UTC, LeoKuD commented on js/index.js
> +  listenerSubmitEditTask = submitEditTask.bind(null, index);
```
myForm.addEventListener('submit', (e) => {
  e.preventDefault();
  if (e.submitter.id === btnSubmitForm.id) {
    taskSubmit();
  } else if (e.submitter.id === btnSubmitEditForm.id) {
    submitEditTask(e.submitter.getAttribute('data-index'));
  }
});
```

2022-01-05 16:57 UTC, LeoKuD commented on js/index.js
> +    e.target.id === 'close-right'
```
 if (
    e.target.id === KEYSVARIABLES.exampleModal ||
    e.target.id === KEYSVARIABLES.btnClose ||
    e.target.id === KEYSVARIABLES.closeRight
  ) {
```

2022-01-05 16:58 UTC, LeoKuD commented on js/index.js
> +    myForm.removeEventListener('submit', taskSubmit);
Fixed

2022-01-05 17:02 UTC, LeoKuD commented on scss/style.scss
> +$bc-color-primary-light: #fff;
```
$bg-color-primary: #1f1d36;
$bg-color-secondary: #3f3351;
$bg-color-tertiary: #e9a6a6;
$priority-color-primary-light: green;
$priority-color-secondary-light: yellow;
$priority-color-tertiary-light: orange;
$bg-color-primary-light: #fff;
$transition: 0.5s;
```
Fixed

2022-01-06 18:32 UTC, Dev1LtJ requested changes
Hello! Almost done. Fix, what you didn't fix before (theme and rename function) and some comments, what I left for your with this review.

2022-01-06 18:32 UTC, Dev1LtJ commented on css/style.css
> +}
You didn't change.

2022-01-06 18:32 UTC, Dev1LtJ commented on css/style.css
> +  transform: translateX(0);
What does it do?

2022-01-06 18:32 UTC, Dev1LtJ commented on index.html
>      </style>
Try to not use this type of styles.

2022-01-06 18:32 UTC, Dev1LtJ commented on js/index.js
> +          ? listCurrentTasks.append(taskItem)
Do not use double `?` It's harder to read.

2022-01-06 18:32 UTC, Dev1LtJ commented on js/index.js
> +function taskTemplate(item, index) {
I meant function name `createTaskNode(item, index)`, but your code is good too.

2022-01-06 18:32 UTC, Dev1LtJ commented on js/index.js
> +  btnSubmitForm.style.display = 'none';
Try to not styling with JS if it is not really needed.

2022-01-06 18:32 UTC, Dev1LtJ commented on js/index.js
> +    btnSubmitEditForm.style.display = 'none';
Try to not styling with JS if it is not really needed.

2022-01-06 18:33 UTC, Dev1LtJ commented on js/index.js
> +  }
Answered on new review.

2022-01-06 18:35 UTC, Dev1LtJ commented on js/index.js
> +});
Don't fixed for now.

2022-01-06 18:35 UTC, Dev1LtJ commented on css/style.css
> +}
Don't fixed for now.

2022-01-06 19:39 UTC, LeoKuD commented on js/index.js
> +      : (item.checked = false);
`  myForm.elements[tasks[index].priority].checked = true;`

2022-01-06 19:44 UTC, LeoKuD commented on js/index.js
> +          ? listCurrentTasks.append(taskItem)
```
      if (selectedSort === KEYSVARIABLES.up) {
        !item.isDone
          ? listCurrentTasks.append(taskItem)
          : listCompletedTasks.append(taskItem);
      } else {
        !item.isDone
          ? listCurrentTasks.prepend(taskItem)
          : listCompletedTasks.prepend(taskItem);
      }
```

2022-01-06 19:54 UTC, LeoKuD commented on js/index.js
> +  }
Fiexed on new review.

2022-01-06 20:40 UTC, LeoKuD commented on js/index.js
> +});
```
toggleTheme.addEventListener('click', () => {
  body.classList.toggle(KEYSVARIABLES.dark);
  body.classList.contains(KEYSVARIABLES.dark)
    ? updateLocalStorage(LOCALSTORAGEKEYS.theme, KEYSVARIABLES.dark)
    : localStorage.removeItem(LOCALSTORAGEKEYS.theme);
});
```

2022-01-06 20:42 UTC, LeoKuD commented on js/index.js
> +});
```
function setTheme() {
  body.classList.contains(KEYSVARIABLES.dark)
    ? updateLocalStorage(LOCALSTORAGEKEYS.theme, KEYSVARIABLES.dark)
    : localStorage.removeItem(LOCALSTORAGEKEYS.theme);
}

toggleTheme.addEventListener('click', () => {
  body.classList.toggle(KEYSVARIABLES.dark);
  setTheme();
});
```

2022-01-06 20:45 UTC, LeoKuD commented on css/style.css
> +}
```
  .Low {
    background-color: $priority-color-primary-light;
  }

  .Medium {
    background-color: $priority-color-secondary-light;
  }

  .High {
    background-color: $priority-color-tertiary-light;
  }
```

2022-01-06 20:46 UTC, LeoKuD commented on css/style.css
> +}
Now whitout light

2022-01-06 20:50 UTC, LeoKuD commented on index.html
>      </style>
Ok, but these styles were on the default pages

2022-01-06 20:50 UTC, LeoKuD commented on css/style.css
> +}
```
  .Low {
    background-color: $priority-color-primary-light;
  }

  .Medium {
    background-color: $priority-color-secondary-light;
  }

  .High {
    background-color: $priority-color-tertiary-light;
  }
```

2022-01-06 20:51 UTC, LeoKuD commented on css/style.css
> +}
Now without light

2022-01-06 20:55 UTC, LeoKuD commented on css/style.css
> +  transform: translateX(0);
Sorry, this is not needed here. Copy-Past!

2022-01-06 21:22 UTC, LeoKuD commented on js/index.js
> +    btnSubmitEditForm.style.display = 'none';
```
  btnSubmitForm.classList.add(KEYSVARIABLES.none);
  btnSubmitForm.classList.remove(KEYSVARIABLES.inlineBlock);
```

2022-01-08 17:52 UTC, maximsan commented on index.html
>      </style>
in any case it's better place styles in file

2022-01-09 08:23 UTC, Dev1LtJ approved these changes
Approved. Wait for @maximsan's review.
P.S. You have not renamed function for now. Rename `taskTemplate` to `createTaskNode` during @maximsan's review.

2022-01-09 10:01 UTC, maximsan requested changes
Hello! I left small comments, please look them through. Ping me when it's ready and I'll approve it. It looks promising 🔥

2022-01-10 08:30 UTC, LeoKuD commented on package.json
> +    "test": "echo \"Error: no test specified\" && exit 1",
Fix

2022-01-10 08:39 UTC, LeoKuD commented on scss/style.scss
> +  }
Corrected.

2022-01-10 08:39 UTC, LeoKuD commented on scss/style.scss
> +  }
```
  .high {
    background-color: $priority-color-tertiary-light;
  }
```

2022-01-10 09:14 UTC, LeoKuD commented on js/index.js
> +};
const VARIABLESTEXTKEYS = {
  close: 'Close',
  cancel: 'Cancel',
  addTaks: 'Add task',
  editTaks: 'Edit task',
  dataIndex: 'data-index',
  inlineBlock: 'inline-block',
  none: 'none',
  save: 'Save',
};
const ELEMENTSKEYS = {
  btnDelete: 'btn-delete',
  btnCompleted: 'btn-completed',
  btnEdit: 'btn-edit',
  exampleModal: 'exampleModal',
  btnClose: 'btn-close',
};

2022-01-10 09:14 UTC, LeoKuD commented on js/index.js
> +};
```
const LOCALSTORAGEKEYS = {
  tasks: 'tasks',
  sorting: 'sorting',
  theme: 'theme',
  dark: 'dark',
  up: 'up',
  down: 'down',
};

const VARIABLESTEXTKEYS = {
  close: 'Close',
  cancel: 'Cancel',
  addTaks: 'Add task',
  editTaks: 'Edit task',
  dataIndex: 'data-index',
  inlineBlock: 'inline-block',
  none: 'none',
  save: 'Save',
};
const ELEMENTSKEYS = {
  btnDelete: 'btn-delete',
  btnCompleted: 'btn-completed',
  btnEdit: 'btn-edit',
  exampleModal: 'exampleModal',
  btnClose: 'btn-close',
};
```

2022-01-10 09:23 UTC, LeoKuD commented on js/index.js
> +};
```
const LOCALSTORAGEKEYS = {
  tasks: 'tasks',
  sorting: 'sorting',
  theme: 'theme',
  dark: 'dark',
  up: 'up',
  down: 'down',
};

const ELEMETSTEXTKEYS = {
  close: 'Close',
  cancel: 'Cancel',
  addTaks: 'Add task',
  editTaks: 'Edit task',
  save: 'Save',
};

const STYLESKEYS = {
  dataIndex: 'data-index',
  inlineBlock: 'inline-block',
  none: 'none',
};

const ELEMENTSKEYS = {
  btnDelete: 'btn-delete',
  btnCompleted: 'btn-completed',
  btnEdit: 'btn-edit',
  exampleModal: 'exampleModal',
  btnClose: 'btn-close',
};
```

2022-01-10 09:27 UTC, LeoKuD commented on js/index.js
> +const myForm = document.forms[0];
```suggestion
const myForm = document.getElementById('my-form');
```

2022-01-10 09:28 UTC, LeoKuD commented on js/index.js
> +const myForm = document.forms[0];
```suggestion
const myForm = document.querySelector('.my-form');
```

2022-01-10 09:43 UTC, LeoKuD commented on js/index.js
> +const titleCompletedBlock = document.getElementById('title-completed-block');
Ok, thanks

2022-01-10 09:44 UTC, LeoKuD commented on js/index.js
> +btnSubmitEditForm.id = 'btnSubmitEditForm';
```
const btnSubmitEditForm = btnSubmitForm.cloneNode(true);
btnSubmitEditForm.id = 'btnSubmitEditForm';
```

2022-01-10 09:44 UTC, LeoKuD commented on js/index.js
> +  const characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
Fixed

2022-01-10 09:46 UTC, LeoKuD commented on js/index.js
> +  return date;
```suggestion
  function checkDate(date) {
  return date < 10 ? `0${date}`: date;
}
```

2022-01-10 09:47 UTC, LeoKuD commented on js/index.js
> +  return date;
```suggestion
  return date;
```
```suggestion
 function checkDate(date) {
  return date < 10 ? `0${date}`: date;
}
```

2022-01-10 09:47 UTC, LeoKuD commented on js/index.js
> +  return date;
```suggestion
  function checkDate(date) {
  return date < 10 ? `0${date}`: date;
}
```

2022-01-10 10:07 UTC, LeoKuD commented on js/index.js
> +};
```
const helpers = {
  generateId: function generateId() {
    let ID = '';
    for (let i = 0; i < 12; i++) {
      ID += characters.charAt(Math.floor(Math.random() * 36));
    }
    return ID;
  },
  checkDate: function checkDate(date) {
    return date < 10 ? `0${date}` : date;
  },
  getDate: function getDate(stamp) {
    const date = new Date(stamp);
    const month =
      date.getMonth() < 9 ? `0${date.getMonth() + 1}` : date.getMonth() + 1;
    const day = this.checkDate(date.getDate());
    const hours = this.checkDate(date.getHours());
    const minutes = this.checkDate(date.getMinutes());
    const fullYear = date.getFullYear();
    return ` ${hours}:${minutes} ${day}.${month}.${fullYear}`;
  },
  setTheme: function setTheme() {
    body.classList.contains(LOCALSTORAGEKEYS.dark)
      ? updateLocalStorage(LOCALSTORAGEKEYS.theme, LOCALSTORAGEKEYS.dark)
      : localStorage.removeItem(LOCALSTORAGEKEYS.theme);
  },
};
```

2022-01-10 10:22 UTC, LeoKuD commented on js/index.js
> +function Task([title, text, priority]) {
```suggestion
function Task(title, text, priority) {

```

2022-01-10 22:48 UTC, maximsan commented on js/index.js
> +};
Please add delimiters. Is it actually easy for you to read it ? Commonly we use PascalCase or
Snake Case (All Caps) - USER_LOGIN_COUNT for constants like this. It's common practice.

2022-01-10 22:51 UTC, maximsan approved these changes
I left 1 more comment. Everything looks good besides it. 

It's approved. Good work :)

2022-01-11 16:11 UTC, merged